#!/usr/bin/env python3
"""
Post-process the contribution snake SVG generated by Platane/snk:
- Injects dark-mode background (#0d1117) and border
- Converts grid cells to rounded geometry
- Adds smooth glowing effect to the snake head and nodes (GitHub green + subtle AWS orange accents)
- Displays verified total contributions dynamically from data/contributions.json
- Updates the cache-buster timestamp in README.md
"""
import json
import os
import re
import sys
import time

USERNAME = os.environ.get("GH_PROFILE_USER", "Hemanth27-DP")


def get_verified_total():
    """Read verified total contributions from data/contributions.json."""
    data_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "data", "contributions.json")
    if os.path.exists(data_path):
        try:
            with open(data_path, "r", encoding="utf-8") as f:
                data = json.load(f)
                return data.get("total_contributions", 0)
        except Exception as e:
            print(f"Warning: could not read {data_path}: {e}", file=sys.stderr)
    return 0


def update_readme_timestamp():
    """Update cache-busting timestamp for the snake SVG in README.md."""
    readme_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "README.md")
    if not os.path.exists(readme_path) and os.path.exists("README.md"):
        readme_path = "README.md"

    if os.path.exists(readme_path):
        try:
            with open(readme_path, "r", encoding="utf-8") as f:
                content = f.read()
            ts = str(int(time.time()))
            content = re.sub(
                r'(\./svgs/github-snake-dark-enhanced\.svg)\?[^\"]*',
                r'\1?v=' + ts,
                content
            )
            with open(readme_path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"Updated README.md snake cache-buster timestamp to v={ts}")
        except Exception as e:
            print(f"Could not update README.md timestamp: {e}", file=sys.stderr)


def enhance():
    total = get_verified_total()
    input_path = os.path.join("svgs", "github-snake-dark.svg")
    enhanced_path = os.path.join("svgs", "github-snake-dark-enhanced.svg")

    if not os.path.exists(input_path):
        if os.path.exists(enhanced_path):
            with open(enhanced_path, "r", encoding="utf-8") as f:
                svg = f.read()
            svg = re.sub(r'Overall Contributions:\s*[\d,]+', f'Overall Contributions: {total:,}', svg)
            with open(enhanced_path, "w", encoding="utf-8") as f:
                f.write(svg)
            print(f"Updated existing enhanced SVG with verified total: {total:,}")
            update_readme_timestamp()
            return
        else:
            print("No snake SVG found to enhance.", file=sys.stderr)
            return

    with open(input_path, "r", encoding="utf-8") as f:
        svg = f.read()

    # 1. Custom CSS and Keyframe animations
    custom_css = """
    @keyframes pop {
        0% { opacity: 0; transform: scale(0.2); }
        60% { opacity: 1; transform: scale(1.1); }
        100% { opacity: 1; transform: scale(1); }
    }
    .total-text { fill: #8b949e; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; font-size: 14px; font-weight: 600; letter-spacing: 0.5px; animation: pop 0.5s ease-out forwards; animation-delay: 3s; opacity: 0; }
    .accent-val { fill: #39d353; font-weight: 700; }
    """

    svg = svg.replace('.c{', '.c{animation-delay:4s !important;')
    svg = svg.replace('.s{', '.s{animation-delay:4s !important;')
    svg = svg.replace('.u{', '.u{animation-delay:4s !important;')
    svg = svg.replace('</style>', custom_css + '</style>')

    # 2. Wrap background cells
    def repl_bg(match):
        full_match = match.group(0)
        x_m = re.search(r'x="([\d.]+)"', full_match)
        y_m = re.search(r'y="([\d.]+)"', full_match)
        if x_m and y_m:
            x = float(x_m.group(1))
            y = float(y_m.group(1))
            wk = (x - 2) / 16
            row = (y - 2) / 16
            delay = round((wk + row * 0.55) / 55 * 3.6, 3)
            # Add subtle rounded corners to rect
            full_match = re.sub(r'rx="[^"]*"', '', full_match)
            full_match = re.sub(r'ry="[^"]*"', '', full_match)
            full_match = full_match.replace('<rect ', '<rect rx="3" ry="3" ')
            return f'<g style="opacity:0; animation: pop 0.5s ease-out forwards; animation-delay: {delay}s; transform-box: fill-box; transform-origin: center;">{full_match}</g>'
        return full_match

    svg = re.sub(r'<rect class="c[^"]*"[^>]*>', repl_bg, svg)

    # 3. Wrap snake rects with glowing orb styling
    def repl_snake(match):
        full_match = match.group(0)
        full_match = re.sub(r'rx="[^"]*"', 'rx="10"', full_match)
        full_match = re.sub(r'ry="[^"]*"', 'ry="10"', full_match)
        full_match = full_match.replace('<rect ', '<rect style="fill: #ffffff !important;" ')
        return f'<g style="opacity:0; animation: pop 0.1s ease-out forwards; animation-delay: 3.9s; transform-box: fill-box; transform-origin: center; filter: drop-shadow(0 0 6px #39d353) drop-shadow(0 0 10px #FF9900); transform: scale(1.35);">{full_match}</g>'

    svg = re.sub(r'<rect class="s[^"]*"[^>]*>', repl_snake, svg)

    # 4. Wrap unvisited path
    def repl_unvisited(match):
        full_match = match.group(0)
        x_m = re.search(r'x="([\d.]+)"', full_match)
        y_m = re.search(r'y="([\d.]+)"', full_match)
        delay = 3.9
        if x_m and y_m:
            x = float(x_m.group(1))
            y = float(y_m.group(1))
            wk = (x - 2) / 16
            row = (y - 2) / 16
            delay = round(3.9 + (wk + row * 0.55) / 55 * 1.5, 3)
        return f'<g style="opacity:0; animation: pop 0.3s ease-out forwards; animation-delay: {delay}s; transform-box: fill-box; transform-origin: center;">{full_match}</g>'

    svg = re.sub(r'<rect class="u[^"]*"[^>]*>', repl_unvisited, svg)

    # 5. Expand height for total text
    def repl_svg(match):
        h = float(match.group(1)) + 60
        return f'height="{h}"'
    svg = re.sub(r'height="([\d.]+)"', repl_svg, svg, count=1)

    def repl_viewbox(match):
        parts = match.group(1).split()
        parts[3] = str(float(parts[3]) + 60)
        return f'viewBox="{" ".join(parts)}"'
    svg = re.sub(r'viewBox="([^"]+)"', repl_viewbox, svg, count=1)

    # Total contribution label
    text_element = f'<text class="total-text" x="12" y="212">Overall Contributions: <tspan class="accent-val">{total:,}</tspan></text>'
    svg = svg.replace('</svg>', f'{text_element}</svg>')

    # Dark background
    if 'style="background-color:' not in svg:
        svg = svg.replace('<svg', '<svg style="background-color: #0d1117;"')

    with open(enhanced_path, "w", encoding="utf-8") as f:
        f.write(svg)
    print(f"Snake SVG successfully enhanced. Overall Contributions: {total:,}")
    update_readme_timestamp()


if __name__ == "__main__":
    enhance()
